on:
  push:
    branches:
      - github-deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: 12

      - name: Install
        run: yarn install

      - name: Deploy to GitHub Pages
        run: |
          git config user.name henry.tran
          git config user.email henry.tran@users.noreply.github.com
          git remote set-url origin https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/YYC-HALT/Emerald-Palace.git
          yarn deploy
